# GitHub Pages Configuration
title: Minimal Status Panel
description: A beautiful Grafana panel plugin for monitoring service status with an intuitive, Uptime Kuma-inspired interface
baseurl: "/Minimal-Status-Panel"
url: "https://perseus985.github.io"

# Use github-pages plugin (includes all necessary plugins)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
navbar:
  - title: Home
    url: /
  - title: Getting Started
    url: /getting-started
  - title: Configuration
    url: /configuration
  - title: Display Modes
    url: /display-modes
  - title: Advanced Usage
    url: /advanced-usage
  - title: API Reference
    url: /api-reference
  - title: FAQ
    url: /faq

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Perseus985/Minimal-Status-Panel"
    - label: "Issues"
      icon: "fas fa-fw fa-bug"
      url: "https://github.com/Perseus985/Minimal-Status-Panel/issues"

# SEO
lang: en
google_analytics: # Add your GA tracking ID here if needed

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/