name: Pull Request

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  test-and-build:
    name: Test & Build PR
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run TypeScript check
      run: npm run typecheck
      
    - name: Run linting
      run: npm run lint
      
    - name: Run tests
      run: npm run test:ci
      
    - name: Build plugin
      run: npm run build
      
    - name: Check build size
      run: |
        echo "## Build Results 📊" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| File | Size |" >> $GITHUB_STEP_SUMMARY
        echo "|------|------|" >> $GITHUB_STEP_SUMMARY
        ls -lh dist/*.js | awk '{print "| " $9 " | " $5 " |"}' >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Total dist size: $(du -sh dist | cut -f1)" >> $GITHUB_STEP_SUMMARY
        
    - name: Upload PR build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pr-build-${{ github.event.number }}
        path: dist/
        retention-days: 7

  comment-pr:
    name: Comment on PR
    runs-on: ubuntu-latest
    needs: test-and-build
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Comment PR
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## ✅ Build Successful!
            
            Your pull request has been built successfully. You can download the build artifacts to test the changes.
            
            ### 📦 Artifacts
            - Build artifacts are available for 7 days
            - Download link will appear in the "Artifacts" section of the workflow run
            
            ### 🧪 Testing
            To test this build:
            1. Download the build artifacts
            2. Extract to your Grafana plugins directory
            3. Restart Grafana
            4. Test the plugin functionality
            
            ---
            *This comment was automatically generated by GitHub Actions*`
          });